# Generated by Django 4.2.6 on 2023-10-12 06:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0003_alter_modeldetails_brand_alter_modeldetails_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('96a64cfd-1530-48ff-9900-2675e0e15b76'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('ba68ddc0-4516-4dce-bd60-9e777ffd068e'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
    ]
