# Generated by Django 4.2.6 on 2023-10-12 13:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0012_youtubevideo_brand_youtubevideo_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='type',
            field=models.CharField(choices=[('short', 'Short'), ('long', 'Long')], default='short', max_length=10),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('a2210140-53cd-423f-8d4b-f1f302d9ff07'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('afcc0775-f05e-4199-a175-9836da404a68'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='model_details',
            field=models.ForeignKey(default=uuid.UUID('4102c0fa-2728-4303-80f2-e2cc50a36ca2'), on_delete=django.db.models.deletion.CASCADE, related_name='ytvideos', to='appv1.modeldetails'),
        ),
    ]
