# Generated by Django 4.2.6 on 2023-10-13 10:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0017_alter_article_publication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='content3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='content4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='image_url1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='image_url2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='image_url3',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('064e1322-e56f-4c57-8e57-359be2a86495'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('b19714e2-ec81-41bb-9bbc-868c2ddc3fe2'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='model_details',
            field=models.ForeignKey(default=uuid.UUID('0e8a8776-f365-497b-b447-bbb8cb9d0fda'), on_delete=django.db.models.deletion.CASCADE, related_name='ytvideos', to='appv1.modeldetails'),
        ),
    ]
