# Generated by Django 3.2.1 on 2023-10-17 11:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0033_auto_20231017_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeldetails',
            name='color',
        ),
        migrations.RemoveField(
            model_name='modeldetails',
            name='connectivity',
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='sar_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('e17e57eb-be74-494a-9e4a-1365e31b4d64'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('cdd440bb-4f8c-49af-a771-22909a443a1b'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='model_details',
            field=models.ForeignKey(default=uuid.UUID('579332f4-b3a5-473d-bf20-87a4c2090e48'), on_delete=django.db.models.deletion.CASCADE, related_name='ytvideos', to='appv1.modeldetails'),
        ),
    ]
