# Generated by Django 3.2.1 on 2023-10-17 11:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0034_auto_20231017_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldetails',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='connectivity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='expandable_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='network_connectivity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='sim_card_slots',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('16127f84-df11-4af3-b12f-37d8737c9bc2'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('86893b21-d348-4b9c-af28-675b88ca3112'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='model_details',
            field=models.ForeignKey(default=uuid.UUID('1a092bf9-8263-4956-bd85-0de3713490a9'), on_delete=django.db.models.deletion.CASCADE, related_name='ytvideos', to='appv1.modeldetails'),
        ),
    ]
