# Generated by Django 3.2.1 on 2023-10-18 07:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0045_auto_20231018_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideoDetails',
            fields=[
                ('video_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('short', 'Short'), ('long', 'Long')], default='short', max_length=10)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('recom', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ytvideo', to='appv1.article')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ytvideo', to='appv1.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ytvideo', to='appv1.category')),
            ],
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('cf566c81-80b1-4367-a034-ea9e2bec6b9d'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('158232e5-4fe7-49d6-8ce9-3baeeebb0572'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
        migrations.DeleteModel(
            name='YouTubeVideo',
        ),
        migrations.AddField(
            model_name='youtubevideodetails',
            name='model_details',
            field=models.ForeignKey(default=uuid.UUID('aaa615fd-90e6-4e0c-a7d6-43d415e8c428'), on_delete=django.db.models.deletion.CASCADE, related_name='ytvideos', to='appv1.modeldetails'),
        ),
    ]
