# Generated by Django 3.2.1 on 2023-10-18 09:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0046_auto_20231018_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeldetails',
            old_name='RAM',
            new_name='ram',
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='img1',
            field=models.URLField(default='https://three2mobiles.onrender.com/api/modeldetails/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='img2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='img3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='img4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('ad61bb44-8847-46ff-a8d8-2e8db60938d7'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('7893f5e6-0be0-493b-96f9-7f801588f633'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
        migrations.AlterField(
            model_name='youtubevideodetails',
            name='model_details',
            field=models.ForeignKey(default=uuid.UUID('32379e60-a364-4257-bf40-5fe1d1de3bd9'), on_delete=django.db.models.deletion.CASCADE, related_name='ytvideos', to='appv1.modeldetails'),
        ),
    ]
