# Generated by Django 3.2.1 on 2023-10-19 05:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0047_auto_20231018_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeldetails',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='modeldetails',
            name='category',
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='brandname',
            field=models.CharField(blank=True, default='just a brand', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='categoryname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Google', 'Google'), ('Vivo', 'Vivo'), ('Realme', 'Realme'), ('Oppo', 'Oppo'), ('Xiaomi', 'Xiaomi'), ('OnePlus', 'OnePlus'), ('Motorola', 'Motorola'), ('Other', 'Other')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='youtubevideodetails',
            name='model_details',
            field=models.ForeignKey(default=uuid.UUID('596848af-51ca-4349-a7be-4482b173cd62'), on_delete=django.db.models.deletion.CASCADE, related_name='ytvideos', to='appv1.modeldetails'),
        ),
    ]
