# Generated by Django 3.2.1 on 2023-10-19 05:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0047_auto_20231018_1437'),
    ]

    operations = [
        
    ]
