# Generated by Django 3.2.1 on 2023-10-19 05:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0048_auto_20231019_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldetails',
            name='brandname',
            field=models.CharField(blank=True, default='just a brand', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='categoryname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Google', 'Google'), ('Vivo', 'Vivo'), ('Realme', 'Realme'), ('Oppo', 'Oppo'), ('Xiaomi', 'Xiaomi'), ('OnePlus', 'OnePlus'), ('Motorola', 'Motorola'), ('Other', 'Other')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('48bd4a9c-7495-4b47-9e51-21c493d11a90'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('782a70b7-cd6e-42c1-b530-11ce146648db'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
        migrations.AlterField(
            model_name='youtubevideodetails',
            name='model_details',
            field=models.ForeignKey(default=uuid.UUID('ddd3c81d-c4f9-4db1-898c-b395c729f66f'), on_delete=django.db.models.deletion.CASCADE, related_name='ytvideos', to='appv1.modeldetails'),
        ),
    ]
