# Generated by Django 3.2.1 on 2023-10-19 08:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0049_auto_20231019_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeldetails',
            old_name='warranty',
            new_name='warranty_duration',
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='antutu_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='antutu_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('92960c66-f3a7-4ae0-9da9-3f7e0391985c'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('d4208d99-ab2a-43a7-8312-ea31723740f9'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
        migrations.AlterField(
            model_name='youtubevideodetails',
            name='model_details',
            field=models.ForeignKey(default=uuid.UUID('7c679cbb-5fc9-49dc-a6c3-4b7d18d956c7'), on_delete=django.db.models.deletion.CASCADE, related_name='ytvideos', to='appv1.modeldetails'),
        ),
    ]
