# Generated by Django 3.2.1 on 2023-10-19 08:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0050_auto_20231019_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeldetails',
            old_name='warranty_duration',
            new_name='warranty',
        ),
        migrations.RemoveField(
            model_name='modeldetails',
            name='antutu_desc',
        ),
        migrations.RemoveField(
            model_name='modeldetails',
            name='antutu_score',
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('5f3e8653-86cd-4148-85f0-8ed650e6b098'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('aac00bcf-a510-4786-b0f2-7f9a184e755b'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
        migrations.AlterField(
            model_name='youtubevideodetails',
            name='model_details',
            field=models.ForeignKey(default=uuid.UUID('38a43877-f1da-44cd-b724-6d654f4df59c'), on_delete=django.db.models.deletion.CASCADE, related_name='ytvideos', to='appv1.modeldetails'),
        ),
    ]
