# Generated by Django 3.2.1 on 2023-10-19 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0057_auto_20231019_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeldetails',
            name='accessibility_features',
        ),
        migrations.RemoveField(
            model_name='modeldetails',
            name='antutu_desc',
        ),
        migrations.RemoveField(
            model_name='modeldetails',
            name='antutu_score',
        ),
        migrations.RemoveField(
            model_name='modeldetails',
            name='gaming_performance',
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('8d7a76fb-4cb3-45aa-9571-333792e7976c'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('7ef2a141-544f-4df7-b87d-9fbcc9e3655d'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
        migrations.AlterField(
            model_name='youtubevideodetails',
            name='model_details',
            field=models.ForeignKey(default=uuid.UUID('b0e4e9e5-8798-4b97-8785-d06236f25506'), on_delete=django.db.models.deletion.CASCADE, related_name='ytvideos', to='appv1.modeldetails'),
        ),
    ]
