# Generated by Django 3.2.1 on 2023-10-20 08:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0060_auto_20231020_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsmodel',
            name='model_details',
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='model_details',
            field=models.ManyToManyField(related_name='modeldetails', to='appv1.TagsModel'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('63ee7aee-6548-4650-ac70-337175940334'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('7fe552cd-9514-487b-aea0-82c33d9577b9'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
        migrations.AlterField(
            model_name='youtubevideodetails',
            name='model_details',
            field=models.ForeignKey(default=uuid.UUID('b83b46e8-f746-4fe2-b34a-cc1b25e41493'), on_delete=django.db.models.deletion.CASCADE, related_name='ytvideos', to='appv1.modeldetails'),
        ),
    ]
