# Generated by Django 3.2.1 on 2023-10-19 09:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0061_auto_20231019_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeldetails',
            name='sar_value',
        ),
        migrations.RemoveField(
            model_name='modeldetails',
            name='special_features',
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('044a9421-7391-440b-999c-725cfe7c50b5'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('2e3110bb-f87d-4d9c-b51c-e3d8554043a0'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
        migrations.AlterField(
            model_name='youtubevideodetails',
            name='model_details',
            field=models.ForeignKey(default=uuid.UUID('7492a5a8-d66f-4047-b212-36d2713b8e72'), on_delete=django.db.models.deletion.CASCADE, related_name='ytvideos', to='appv1.modeldetails'),
        ),
    ]
