# Generated by Django 3.2.1 on 2023-10-20 08:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0061_auto_20231020_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeldetails',
            old_name='model_details',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('cf5d34ee-a0dd-497a-8380-5753d44bbbc4'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('20edfb48-c31c-4528-a6a3-b4da386cf906'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
        migrations.AlterField(
            model_name='youtubevideodetails',
            name='model_details',
            field=models.ForeignKey(default=uuid.UUID('ed756c4f-ff09-43a6-921c-fee17a91455f'), on_delete=django.db.models.deletion.CASCADE, related_name='ytvideos', to='appv1.modeldetails'),
        ),
    ]
