# Generated by Django 3.2.1 on 2023-10-20 08:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0062_auto_20231020_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url1',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url2',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url3',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('3881aa4f-6e43-4186-9d28-0be1700967b5'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('ca67d63f-d080-45e3-bf7d-fb5b130bb95d'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
        migrations.AlterField(
            model_name='youtubevideodetails',
            name='model_details',
            field=models.ForeignKey(default=uuid.UUID('dea25aca-5730-4071-baa7-b3beaed0e67a'), on_delete=django.db.models.deletion.CASCADE, related_name='ytvideos', to='appv1.modeldetails'),
        ),
    ]
