# Generated by Django 4.2.6 on 2023-10-12 06:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='brands',
            field=models.ManyToManyField(blank=True, to='appv1.brand'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appv1.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='products',
            field=models.ManyToManyField(blank=True, to='appv1.mobile'),
        ),
        migrations.AddField(
            model_name='category',
            name='mobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appv1.mobile'),
        ),
        migrations.AddField(
            model_name='category',
            name='tv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appv1.tv'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appv1.brand'),
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('209371e3-c1cb-4c43-9b02-0e8c3ba86647'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('49cef61d-674d-48fd-8f84-3973d9e363c4'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
        migrations.AddField(
            model_name='tv',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appv1.brand'),
        ),
    ]
