# Generated by Django 4.2.6 on 2023-10-12 06:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0004_alter_modeldetails_brand_alter_modeldetails_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('4b7e2a2a-193a-4d85-9dd1-8c27c9bfa209'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('05a90564-12bb-40a3-8525-f38ddeff4498'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
        migrations.DeleteModel(
            name='CategoryBrandRelation',
        ),
    ]
