# Generated by Django 4.2.6 on 2023-10-12 10:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0008_alter_category_name_alter_modeldetails_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldetails',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('80240190-7c9f-4e6c-b551-afcc99695670'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('445b19e1-9f69-4fac-a22e-7fc5608bec60'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
    ]
