# Generated by Django 4.2.6 on 2023-10-12 12:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0010_modeldetails_ram_modeldetails_battery_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='products',
            field=models.ManyToManyField(blank=True, to='appv1.modeldetails'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('30983813-41ab-49b2-a586-1e89105fb186'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('e9231d8f-77ab-4329-8ed9-16d99468a30e'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
    ]
