# Generated by Django 4.2.6 on 2023-10-12 13:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0011_alter_article_products_alter_modeldetails_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ytvideo', to='appv1.brand'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ytvideo', to='appv1.article'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='model_details',
            field=models.ForeignKey(default=uuid.UUID('087b381e-98a5-4a75-8571-ab3a1a6fa837'), on_delete=django.db.models.deletion.CASCADE, related_name='ytvideos', to='appv1.modeldetails'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('70654507-078a-48d9-a419-57d5b3bb9e71'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('0bf76b29-b109-4662-97da-602a9ca56a7c'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
    ]
