# Generated by Django 4.2.6 on 2023-10-14 10:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0019_alter_modeldetails_brand_alter_modeldetails_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('f9b7d374-e22c-4a79-838d-2fbc27d0f7c0'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('3a88f47d-a520-44fe-bc6c-67d3b20c223f'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='model_details',
            field=models.ForeignKey(default=uuid.UUID('67eda33d-7f3b-456b-946c-b4740b4df712'), on_delete=django.db.models.deletion.CASCADE, related_name='ytvideos', to='appv1.modeldetails'),
        ),
        migrations.CreateModel(
            name='ModelDetailTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('Latest', 'Latest'), ('BestCamera', 'BestCamera'), ('Performance', 'Performance'), ('Gaming', 'Gaming'), ('Battery', 'Battery'), ('Iphone', 'Iphone'), ('Samsung', 'Samsung'), ('120hz', '120hz'), ('90hz', '90hz'), ('Nothing', 'Nothing'), ('Low-price', 'Low-Price')], max_length=30, unique=True)),
                ('model_details', models.ManyToManyField(related_name='tags', to='appv1.modeldetails')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('Latest', 'Latest'), ('BestDeals', 'BestDeals'), ('Comparison', 'Comparison'), ('Upcoming', 'Upcoming'), ('HotDeals', 'HotDeals'), ('News', 'News'), ('Mobiles', 'Mobiles'), ('Laptops', 'Laptops'), ('Smartwatch', 'Smartwatch'), ('Earphones', 'Earphones'), ('Gadget', 'Gadget')], max_length=30, unique=True)),
                ('articles', models.ManyToManyField(related_name='tags', to='appv1.article')),
            ],
        ),
    ]
