# Generated by Django 4.2.6 on 2023-10-14 10:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0029_alter_modeldetails_brand_alter_modeldetails_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('Latest', 'Latest'), ('BestDeals', 'BestDeals'), ('Comparison', 'Comparison'), ('Upcoming', 'Upcoming'), ('HotDeals', 'HotDeals'), ('News', 'News'), ('Mobiles', 'Mobiles'), ('Laptops', 'Laptops'), ('Smartwatch', 'Smartwatch'), ('Earphones', 'Earphones'), ('Gadget', 'Gadget')], max_length=30, unique=True)),
                ('articles', models.ManyToManyField(related_name='tags', to='appv1.article')),
            ],
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('Latest', 'Latest'), ('BestCamera', 'BestCamera'), ('Performance', 'Performance'), ('Gaming', 'Gaming'), ('Battery', 'Battery'), ('Iphone', 'Iphone'), ('Samsung', 'Samsung'), ('120hz', '120hz'), ('90hz', '90hz'), ('Nothing', 'Nothing'), ('Low-price', 'Low-Price')], max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='modeldetailtags',
            name='model_details',
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='brand',
            field=models.ForeignKey(default=uuid.UUID('25707282-e201-4ea8-b89d-a37cf65d8ae3'), on_delete=django.db.models.deletion.CASCADE, to='appv1.brand'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('cdd22073-7250-4c64-8a59-f2b0fbf9c360'), on_delete=django.db.models.deletion.CASCADE, to='appv1.category'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='model_details',
            field=models.ForeignKey(default=uuid.UUID('065d3f3f-6906-4e6b-93b1-a50c1eec09f1'), on_delete=django.db.models.deletion.CASCADE, related_name='ytvideos', to='appv1.modeldetails'),
        ),
        migrations.DeleteModel(
            name='ArticleTags',
        ),
        migrations.DeleteModel(
            name='ModelDetailTags',
        ),
        migrations.AddField(
            model_name='tagsmodel',
            name='model_details',
            field=models.ManyToManyField(related_name='tags', to='appv1.modeldetails'),
        ),
    ]
